export const SET_STOCK_PRICE_GENERATOR = 'SET_STOCK_PRICE_GENERATOR';
export const SET_STOCK_PRICE_GENERATOR_FAILED = 'SET_STOCK_PRICE_GENERATOR_FAILED';

export const SET_SOCIAL_MEDIA_COUNTER_FACEBOOK = 'SET_SOCIAL_MEDIA_COUNTER_FACEBOOK';
export const SET_SOCIAL_MEDIA_COUNTER_TWITTER = 'SET_SOCIAL_MEDIA_COUNTER_TWITTER';
export const SET_SOCIAL_MEDIA_COUNTER_INSTAGRAM = 'SET_SOCIAL_MEDIA_COUNTER_INSTAGRAM';
export const SET_SOCIAL_MEDIA_COUNTER_FAILED = 'SET_SOCIAL_MEDIA_COUNTER_FAILED';

export const SET_RECOMMENDED_ALGHORITHM = 'SET_RECOMMENDED_ALGHORITHM';
export const SET_RECOMMENDED_ALGHORITHM_FAILED = 'SET_RECOMMENDED_ALGHORITHM_FAILED';


export const FETCH_POSTS = 'FETCH_POSTS';